<?php
/*******************************************************************************
 * Copyright (c) 2022. Ankio. All Rights Reserved.
 ******************************************************************************/
/**
 * Package: app\controller\index
 * Class Install
 * Created By ankio.
 * Date : 2023/5/19
 * Time : 12:20
 * Description :
 */

namespace app\controller\index;

use cleanphp\base\Controller;
use cleanphp\base\Request;
use cleanphp\base\Response;
use cleanphp\base\Variables;
use cleanphp\cache\Cache;
use cleanphp\engine\EngineManager;

class Install extends Controller
{
    function index(): void
    {

        if (!empty(Cache::init(0,Variables::getCachePath('cleanphp',DS))->get("install.lock"))) {
            Response::location(url('index', 'main', 'index'));
        }
        $functions = array(
            0 => 'str_replace',
            1 => 'time',
            2 => 'strtotime',
            3 => 'date',
            4 => 'number_format',
            5 => 'array_merge',
            6 => 'md5',
            7 => 'file_get_contents',
            8 => 'getimagesizefromstring',
            9 => 'image_type_to_extension',
            10 => 'imagecreatefromstring',
            11 => 'min',
            12 => 'imagecreatetruecolor',
            13 => 'imagecopyresampled',
            14 => 'imagedestroy',
            15 => 'strrchr',
            16 => 'strtolower',
            17 => 'in_array',
            18 => 'header',
            19 => 'scandir',
            20 => 'filemtime',
            21 => 'unlink',
            22 => 'is_file',
            23 => 'substr',
            24 => 'strrpos',
            25 => 'file_exists',
            26 => 'trim',
            27 => 'explode',
            28 => 'chop',
            29 => 'strstr',
            30 => 'mb_strlen',
            31 => 'str_repeat',
            32 => 'strlen',
            33 => 'strspn',
            34 => 'method_exists',
            35 => 'strpos',
            36 => 'strcspn',
            37 => 'preg_match',
            38 => 'preg_quote',
            39 => 'ltrim',
            40 => 'preg_replace',
            41 => 'end',
            42 => 'substr_count',
            43 => 'count',
            44 => 'preg_match_all',
            45 => 'array_slice',
            46 => 'array_combine',
            47 => 'strpbrk',
            48 => 'is_string',
            49 => 'call_user_func',
            50 => 'htmlspecialchars',
            51 => '_',
            52 => 'version_compare',
            53 => 'uniqid',
            54 => 'rand',
            55 => 'intval',
            56 => 'bcmul',
            57 => 'bcdiv',
            58 => 'array_reverse',
            59 => 'json_encode',
            60 => 'password_hash',
            61 => 'json_decode',
            62 => 'ksort',
            63 => 'hash_hmac',
            64 => 'http_build_query',
            65 => 'log',
            66 => 'fopen',
            67 => 'feof',
            68 => 'fgets',
            69 => 'sizeof',
            70 => 'fclose',
            71 => 'ob_start',
            72 => 'ob_get_clean',
            73 => 'parse_url',
            74 => 'parse_str',
            75 => 'urldecode',
            76 => 'ini_get',
            77 => 'is_writable',
            78 => 'is_readable',
            79 => 'function_exists',
            80 => 'extension_loaded',
            81 => 'sprintf',
            82 => 'base64_encode',
            84 => 'stream_wrapper_register',
            87 => 'stat',
            88 => 'call_user_func_array',
            89 => 'func_get_args',
            90 => 'serialize',
            91 => 'unserialize',
            92 => 'spl_object_hash',
            94 => 'extract',
            95 => 'is_array',
            96 => 'is_object',
            97 => 'defined',
            98 => 'define',
            101 => 'var_export',
            102 => 'dirname',
            108 => 'array_intersect_key',
            109 => 'array_flip',
            110 => 'array_map',
            111 => 'implode',
            115 => 'array_keys',
            117 => 'sha1',
            118 => 'token_get_all',
            122 => 'is_null',
            123 => 'array_shift',
            125 => 'hash_equals',
            126 => 'error_reporting',
            127 => 'ini_set',
            128 => 'microtime',
            130 => 'class_exists',
            131 => 'class_implements',
            132 => 'is_dir',
            133 => 'ucfirst',
            135 => 'get_class_methods',
            136 => 'round',
            137 => 'opcache_reset',
            138 => 'get_class',
            140 => 'mb_substr',
            143 => 'sys_get_temp_dir',
            144 => 'file_put_contents',
            147 => 'opendir',
            148 => 'readdir',
            149 => 'closedir',
            150 => 'rmdir',
            152 => 'copy',
            153 => 'mkDir',
            154 => 'clearstatcache',
            155 => 'mkdir',
            156 => 'str_starts_with',
            158 => 'fwrite',
            160 => 'Log',
            162 => 'floor',
            163 => 'str_pad',
            164 => 'strval',
            165 => 'setType',
            168 => 'flock',
            170 => 'get_object_vars',
            171 => 'hash',
            174 => 'str_contains',
            175 => 'mb_detect_encoding',
            176 => 'mb_detect_order',
            177 => 'mb_convert_encoding',
            178 => 'pathinfo',
            179 => 'array_key_exists',
            180 => 'debug_backtrace',
            181 => 'var_dump',
            182 => 'is_int',
            184 => 'is_bool',
            185 => 'boolval',
            186 => 'is_float',
            187 => 'floatval',
            188 => 'is_double',
            189 => 'doubleval',
            190 => 'mt_rand',
            193 => 'addslashes',
            194 => 'Date',
            196 => 'realpath',
            197 => 'md5_file',
            198 => 'basename',
            200 => 'preg_replace_callback',
            201 => 'file',
            203 => 'highlight_string',
            205 => 'gmdate',
            206 => 'print_r',
            207 => 'spl_autoload_register',
            208 => 'is_iterable',
            212 => 'gettype',
            213 => 'array_pop',
            215 => 'ob_get_contents',
            216 => 'ob_end_clean',
            217 => 'pack',
            218 => 'json_last_error_msg',
            220 => 'http_response_code',
            222 => 'headers_sent',
            223 => 'session_status',
            224 => 'session_set_cookie_params',
            225 => 'session_start',
            226 => 'session_id',
            227 => 'session_destroy',
            228 => 'setcookie',
            230 => 'date_default_timezone_set',
            232 => 'gethostbyname',
            233 => 'gethostname',
            234 => 'set_error_handler',
            235 => 'set_exception_handler',
            236 => 'error_clear_last',
            239 => 'array_unique',
            241 => 'array_change_key_case',
            242 => 'str_ireplace',
            243 => 'ignore_user_abort',
            244 => 'connection_aborted',
            246 => 'stream_context_create',
            247 => 'stream_socket_client',
            248 => 'usleep',
            249 => 'set_time_limit',
            250 => 'ob_get_length',
            251 => 'ob_end_flush',
            252 => 'flush',
            259 => 'openssl_digest',
            261 => 'openssl_encrypt',
            262 => 'openssl_decrypt',
            263 => 'openssl_pkey_new',
            264 => 'openssl_pkey_export',
            265 => 'openssl_pkey_get_details',
            268 => 'openssl_public_encrypt',
            270 => 'openssl_pkey_get_public',
            271 => 'openssl_private_decrypt',
            272 => 'base64_decode',
            273 => 'openssl_pkey_get_private',
            274 => 'openssl_private_encrypt',
            275 => 'openssl_public_decrypt',
            277 => 'array_values',
            279 => 'rtrim',
            283 => 'getOpt',
            284 => 'reset',
            291 => 'join',
            294 => 'COUNT',
            295 => 'ceil',
            298 => 'max',
            299 => 'range',
            303 => 'str_ends_with',
            316 => 'get_called_class',
            326 => 'strtoupper',
            335 => 'is_callable',
            336 => 'curl_init',
            337 => 'curl_setopt',
            339 => 'curl_exec',
            340 => 'curl_close',
            341 => 'mail',
            343 => 'php_uname',
            346 => 'property_exists',
            348 => 'stripos',
            353 => 'error_log',
            354 => 'htmlentities',
            356 => 'trigger_error',
            358 => 'mb_check_encoding',
            361 => 'idn_to_ascii',
            362 => 'tempnam',
            364 => 'openssl_pkcs7_sign',
            367 => 'openssl_error_string',
            368 => 'random_bytes',
            369 => 'openssl_random_pseudo_bytes',
            371 => 'chunk_split',
            372 => 'quoted_printable_encode',
            374 => 'date_default_timezone_get',
            375 => 'filter_var',
            376 => 'is_numeric',
            378 => 'ord',
            379 => 'openssl_sign',
            380 => 'openssl_pkey_free',
            387 => 'ctype_alnum',
            392 => 'addcslashes',
            396 => 'array_search',
            397 => 'array_unshift',
            400 => 'hexdec',
            403 => 'array_filter',
            404 => 'rawurldecode',
            406 => 'html_entity_decode',
            407 => 'strip_tags',
            411 => 'restore_error_handler',
            412 => 'fsockopen',
            413 => 'is_resource',
            415 => 'stream_set_timeout',
            416 => 'stream_get_meta_data',
            419 => 'stream_select',
            421 => 'stream_socket_enable_crypto',
            424 => 'chr',
            428 => 'usort',
            429 => 'constant',
            430 => 'base_convert',
            431 => 'dechex',
            432 => 'preg_split',
            440 => 'php_strip_whitespace',
            441 => 'imagecreate',
            442 => 'imagecolorallocate',
            443 => 'imageline',
            445 => 'imagesetpixel',
            446 => 'imagettftext',
            448 => 'imagejpeg',
            451 => 'imagecreatefromgif',
            452 => 'imagecreatefromjpeg',
            453 => 'imagecreatefrompng',
            454 => 'imagecreatefrombmp',
            455 => 'imagesx',
            456 => 'imagesy',
            459 => 'mb_internal_encoding',
            460 => 'imagefilledellipse',
            461 => 'imagecolortransparent',
            462 => 'imagepng',
            467 => 'imagefilledrectangle',
            468 => 'imagescale',
            470 => 'imagegif',
            473 => 'array_chunk',
            474 => 'get_resource_type',
            475 => 'imagefilter',
            476 => 'imagecolorat',
            477 => 'imagecolorsforindex',
            479 => 'array_splice',
            481 => 'array_fill',
            483 => 'rewind',
            484 => 'array_column',
            485 => 'abs',
            486 => 'mb_list_encodings',
            487 => 'iconv',
            488 => 'exp',
            490 => 'sqrt',
            491 => 'is_nan',
            494 => 'str_split',
            496 => 'curl_getinfo',
            498 => 'curl_errno',
            499 => 'curl_error',
            500 => 'stream_get_contents',
            502 => 'getmypid',
            503 => 'sleep',
            506 => 'sort',
            510 => 'password_verify',
            513 => 'move_uploaded_file',
        );

        $unsupported = [];
        foreach ($functions as $function) {
            if (!function_exists($function)) {
                $unsupported[] = $function;
            }
        }
        EngineManager::getEngine()->setLayout("layout")
            ->setData("functions", $unsupported)
            ->setData("domain", Request::getDomainNoPort())
            ->setData("isDocker", getenv('DOCKER_CONTAINER'));

    }



}