name: Release

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  pull-requests: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag name
        id: get_tag
        run: echo ::set-output name=tag_name::$(git describe --tags --abbrev=0)
      - name: Remove "v" from tag name
        id: remove_v
        run: echo ::set-output name=tag_name_without_v::${{ steps.get_tag.outputs.tag_name.replace('v', '') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring
      - name: Install dependencies with Yarn
        run: |
          chmod +x /src/cleanphp/release/clean
          ./src/cleanphp/release/clean release -v=${{ steps.remove_v.outputs.tag_name_without_v }} -n=vpay
          ./src/cleanphp/release/clean release -v=${{ steps.remove_v.outputs.tag_name_without_v }} -n=vpay_bt -f=build_bt.php
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: true
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            dist/vpay_*.zip
